### ISSUE TITLE
Navigation stopped working

### ISSUE THREAD

**Issue by mikebtp** [helgatheviking/Simple-User-Listing#14]

**Comment by helgatheviking** [comment]
Why did you delete the description? by itself, "navigation stopped working" isn't much to go on. Please elaborate: explain your setup, what shortcode attributes you are using, how many users you expect to see total, test without any other plugins active, re-save permalinks.

**Comment by mikebtp** [comment]
Great. Thanks

**Comment by mikebtp** [comment]
Hi Kathy,

Well I'm sufficiently baffled. I deactivated each plugin (8) then tried SUL
with no change (or fix). I then reactivated them all and for whatever
reason, using [userlist], it started working properly. I then
added  meta_key="last_name" orderby="meta_value" order="ASC" inside the
brackets as shown in your FAQ and that worked for one Next click then it
failed again as before (Page Not Found etc.). I changed shortcode back to
[userlist] and problem continues. I can go from Page 1 to Page 2 correctly
but it fails from there (Next & Previous).

I do see what the problem is and will look into why. What is happening is
when I click Next or Previous it goes to the "correct" page but it is
adding text to the url.
Instead of being this: http://127.0.0.1/chs69/classmates/page/2/
it changes to this: http://127.0.0.1/chs69/chs69/classmates/page/2/?paged=3
If I manually remove the extra chs69 it opens correctly.

Not sure why this is so intermittent or how it occurrs.

I'm using [userlist] or [userlist meta_key="last_name" orderby="meta_value"
order="ASC"] as the only text on a Page that has a menu link to that page.

I know you're busy so I'll keep trying to figure this out. I'm sorry I'm
not more proficient with php and wordpress but my background is C# so I'm a
bit slow here (and in most things these days:-).

Thanks for any help,

Mike Grice

G.A.S. Productions, Inc.

Video Creation, Editing, Production

mike@gasproductions.net

mike@griceland.net

 "All politicians should be limited to two terms, one in office and one in
prison." anonymous

**Comment by mikebtp** [comment]
Well I figured it out. For whatever reason, my Permalink setting was set to
Post Name and when I set it to Plain the Next & Previous buttons worked
correctly. Sorry about that.

Mike Grice

G.A.S. Productions, Inc.

Video Creation, Editing, Production

mike@gasproductions.net

mike@griceland.net

 "All politicians should be limited to two terms, one in office and one in
prison." anonymous

**Comment by helgatheviking** [comment]
Thanks for the information.

>Well I figured it out. For whatever reason, my Permalink setting was set to Post Name and when I set it to Plain the Next & Previous buttons worked correctly. Sorry about that.

No need to apologize. That's still an issue b/c I expect it to work when pretty permalinks are enabled (as few people use standard permalinks) and tells me that I may have introduced an error recently with this change: https://github.com/helgatheviking/Simple-User-Listing/commit/070144e2798ec2b887c91818d9a93f858fc5cc5e

I was trying to use whatever the current URL is b/c someone else didn't want to limit it to just the permalink, but that may have created a new problem with pagination.

**Comment by mikebtp** [comment]
Well I did some more testing and this is what I came up with considering my
limited knowledge.
When I set the Permalink to the first option, "Plain", the Next and
Previous buttons worked fine but Search stopped working. It took me to my
Home page.
If I set Permalink to "Day and name", "Month and name", "Numeric",
everything seemed to work fine. If I used "Post name" and "Custom..." with
the last 3 options (postname, category, author) the Next & Previous buttons
broke but using the Date fields worked fine (didn't try Time fields).

My guess, assuming category is a string field, is that the fields that
would contain strings are problematic whereas those of numeric values seem
to work, although "Day and name" and "Month and name" worked. Just a guess.

I've got it working now so thanks for your help.

Mike Grice

G.A.S. Productions, Inc.

Video Creation, Editing, Production

mike@gasproductions.net

mike@griceland.net

 "All politicians should be limited to two terms, one in office and one in
prison." anonymous

**Comment by helgatheviking** [comment]
I can see that the next links are funky, eg: 
https://wc34-helgatheviking.c9users.io/directory/page/4/?paged=5

But since `page/4/` and `?paged=5` are both the same variable from WP's eye, it is correctly resolving for me to:
https://wc34-helgatheviking.c9users.io/directory/page/5/

Hmmm... I may go back to using the permalink, but allow it to be filtered for the 1 or 2 random people who need more than that.

**Comment by mikebtp** [comment]
Sure. I'll be able to get to it later today.

**Comment by mikebtp** [comment]
get_pagenum_link does work fine.

Mike Grice

G.A.S. Productions, Inc.

Video Creation, Editing, Production

mike@gasproductions.net

mike@griceland.net

 "All politicians should be limited to two terms, one in office and one in
prison." anonymous

**Comment by mikebtp** [comment]
Hi Kathy,

I have a question about doing something that may not be possible (I haven't
found it online). Is it possible to add a link to each user in your list
that would allow another user to view (not edit) that user's profile?

Thanks,

Mike Grice

G.A.S. Productions, Inc.

Video Creation, Editing, Production

mike@gasproductions.net

mike@griceland.net

 "All politicians should be limited to two terms, one in office and one in
prison." anonymous

**Comment by helgatheviking** [comment]
@mikebtp You can edit the content any way you like by overriding the templates. 

For example, [here](https://github.com/helgatheviking/Simple-User-Listing/blob/master/templates/content-author.php#L24-L33) there is a link to the author's archive if the author has more than 1 post. You can modify that to always display and then modify your author's archive to display more info about the user. Or you could take some other route towards displaying the user profiles... that's a bit beyond the purview of this plugin.
