### ISSUE TITLE
Remove the Search Input code no longer works

### ISSUE THREAD

**Issue by tibesararchives** [helgatheviking/Simple-User-Listing#22]
Not sure when this occurred; but the functions.php code (listed in the FAQ tab) for removing the Search Input no longer works. 

I use the Code Snippets plugin for all functions.php changes.

Could you please update this code? 

Thank you very much!

**Comment by helgatheviking** [comment]
Output functionality all got converted into [template functions](https://github.com/helgatheviking/Simple-User-Listing/blob/trunk/includes/simple-user-listing-template-functions.php)

Looks like the docs need updating.i think it should be something like this, but can't test at the moment.

```
function remove_SUL_search() {
    remove_action( 'simple_user_listing_before_loop',   'sul_template_user_search' );
}
add_action( 'simple_user_listing_before_loop', 'remove_SUL_search', 1 );
```

```

**Comment by tibesararchives** [comment]
That worked.

Thank you Kathy!

**Comment by helgatheviking** [comment]
Let's leave it open so I remember to update the readme 😂
