### ISSUE TITLE
improve sanitization

### ISSUE THREAD

**Issue by helgatheviking** [helgatheviking/Simple-User-Listing#24]
Not entirely sure what specifically, but SUL has a vulnerability of some sort:

https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/simple-user-listing/simple-user-listing-192-reflected-cross-site-scripting-via-as

**Comment by Ravavyr** [comment]
![F_J5gNBWEAAt9cs](https://github.com/helgatheviking/Simple-User-Listing/assets/44875133/3974e0cd-5cf8-4ac9-8c84-2b6d5134aef1)

The GET processing in this function doesn't validate it, perhaps it's the issue.

Hope that helps you solve it :)
