### ISSUE TITLE
FQDN in Picture-Path

### ISSUE THREAD

**Issue by stkjj** [helgatheviking/Simple-User-Listing#5]
Images from local source are linked als 

< img src="http:/fqd.name/wp-content/plugins/user-avatar/user-avatar-pic.php?src=http://fqd.name/wp-content/uploads/avatars/3/picture.jpg&amp;w=90&amp;id=3&amp;random=1406624605" alt="" class="avatar  avatar-90  photo user-3-avatar" width="90" height="90" >

using the http-request within the ?src-Parameter fails when using security tools like iThemes Security which allows to rewrite such requests for security-reasons (Cross-Site-Scripting-Attack).

Better would be to use relative paths like

< img src="http:/fqd.name/wp-content/plugins/user-avatar/user-avatar-pic.php?src=/wp-content/uploads/avatars/3/picture.jpg&amp;w=90&amp;id=3&amp;random=1406624605" alt="" class="avatar  avatar-90  photo user-3-avatar" width="90" height="90" >

**Comment by helgatheviking** [comment]
SUL only uses `get_avatar()`. If you are using User Avatar for local avatars it is on that plugin to provide the correct source URL.
