### ISSUE TITLE
How to list admin approved users

### ISSUE THREAD

**Issue by rijosh** [helgatheviking/Simple-User-Listing#8]
I need to list all admin approved users. don't show admin declined users....

**Comment by helgatheviking** [comment]
This is not a support forum. Please review the documentation here or at https://wordpress.org/plugins/simple-user-listing/ I have no idea what "admin approved" means or how you are approving users, but if you can figure out how to query for them, then you can use SUL to display them as SUL is based largely on [`WP_User_Query`](https://codex.wordpress.org/Class_Reference/WP_User_Query).
