### ISSUE TITLE
Adjusting the number of users displayed per page

### ISSUE THREAD

**Issue by mkoller** [helgatheviking/Simple-User-Listing#9]
I have custom template to display all the users on my WordPress site. I'm using the following function in my template to display all the Authors.

`<?php echo do_shortcode("[userlist]"); ?>`

This works perfectly, but I would like to display all the Authors without navigating to a second page. I currently have my Reading Settings set to 10 post per page and I have 17 users. I have copied the `content-author.php` , `navigation-author.php` and `search-author.php` to my theme. What is the best way to override the `wp_pagenavi` to display all my users?

**Comment by mkoller** [comment]
Fixed, `<?php echo do_shortcode('[userlist number="50"]'); ?>`

**Comment by helgatheviking** [comment]
Or you can use `[userlist number="-1"]` to retrieve all.  the SUL shortcode supports almost all of the `WP_User_Query` parameters.
